### ISSUE TITLE
The filters don't work in macOS

### ISSUE THREAD

**Issue by rogerluan** [Oliver-Binns/Conferences#17] opened 2023-05-04 23:27 UTC
Hi there! 👋 

Great app idea! 😁  Just downloaded it and noticed the filters don't work in macOS (which works like an iPad app, so maybe the iPad version is also not working?). Screenshot attached:

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/8419048/236350854-92cf8b68-b458-4fe6-8a24-4800f5573040.png">

**Comment by Oliver-Binns** [comment] 2023-06-21 22:03
Agree it looks like an iPad related issue to, I've managed to reproduce myself, so will attempt a fix:
<img width="1112" alt="image" src="https://github.com/Oliver-Binns/Conferences/assets/5354593/745c5828-65c4-462e-8d9a-e093f778f570">

I've also spun up a related issue #24 to ensure Mac is supported as a native platform rather than getting the iPad implementation.

**Comment by Oliver-Binns** [comment] 2023-07-16 07:52
Fixed in latest TestFlight beta, will be deployed to App Store shortly
https://github.com/Oliver-Binns/Conferences/pull/25

**Closed by Oliver-Binns** 2023-07-16 07:52 UTC
Labels: bug
